import discord

def create_invite_info_embed(invite):
    embed = discord.Embed(
        title = f"#{invite.channel.name} Invite",
        description = f"Url: {invite.url}",
        url = invite.url,
        color = discord.Color.green()
    )
    embed.add_field(
        name="Guild: ",
        value=invite.guild.name,
        inline=True
    )
    embed.add_field(
        name="Generated By: ",
        value=invite.inviter,
        inline=True
    )
    embed.add_field(
        name="Code: ",
        value= invite.code,
        inline=True
    )
    embed.add_field(
        name="Max Age: ",
        value=invite.max_age,
        inline=True
    )
    embed.add_field(
        name="Max Uses: ",
        value=invite.max_uses,
        inline=True
    )
    embed.add_field(
        name="Uses: ",
        value=invite.uses,
        inline=True
    )
    embed.add_field(
        name="Temporary: ",
        value=invite.temporary,
        inline=True
    )
    embed.add_field(
        name="Active: ",
        value=not invite.revoked,
        inline=True
    )
    embed.add_field(
        name="Created: ",
        value=invite.created_at,
        inline=True
    )
    return embed